services:
  steamcmd-vitamined:
    image: "${IMAGE_REF:-steamcmd-vitamined:latest}"
    build:
      context: .
      dockerfile: Dockerfile
      target: steamcmd-vitamined-final
      args:
        USER_ID: 1000
    restart: unless-stopped
